package cz.krystofcejchan.enums_annotations_exceptions.enums;

public enum ExternalFileNames {
    POKEGIF, GETSONGSEARCHRES, GETTHEMOSTSUITABLESONG, SOUNDFILETOTEXT, TRANSLATOR,
    TRANSLATORCUSTOM, YTSEARCH, PUBLIC_PLAYLISTS_DB, PRIVATE_PLAYLISTS_DB
}
