package cz.krystofcejchan.link_to_externalfiles;

public enum ExternalFileNamesE {
    POKEGIF, GETSONGSEARCHRES, GETTHEMOSTSUITABLESONG, SOUNDFILETOTEXT, TRANSLATOR,
    TRANSLATORCUSTOM, YTSEARCH, PUBLIC_PLAYLISTS_DB, PRIVATE_PLAYLISTS_DB, RANDOMFACTS
}
